package workloadstats.utils;

/**
 *
 * @author Ilkka
 */
public enum Stat2 {
        
    LECTURES_CONFIRMED,
    LECTURES_CANCELLED,
    LECTURES_TENTATIVE,
    EXERCISES_CONFIRMED,
    EXERCISES_CANCELLED,
    EXERCISES_TENTATIVE,
    PERSONAL_CONFIRMED,
    PERSONAL_CANCELLED,
    PERSONAL_TENTATIVE,
    TEAMWORK_CONFIRMED,
    TEAMWORK_CANCELLED,
    TEAMWORK_TENTATIVE,
    EXAM_CONFIRMED,
    EXAM_CANCELLED,
    EXAM_TENTATIVE,
    CONFIRMED_DURATION,
    CANCELLED_DURATION,
    TENTATIVE_DURATION,    
    TOTAL_DURATION;


}
